### ISSUE TITLE
Core Manager is showing empty list

### ISSUE THREAD

**Issue by shahzadgodil** [vanstinator/core-manager#23]
Hello,

I have installed core manager but it is showing an empty list

https://tinyurl.com/y4e4fv2u

Please help

**Comment by jackaroo9** [comment]
same issue

**Comment by jackaroo9** [comment]
solved for me - was missing 'Game Core' folder - Created empty folder

**Comment by vanstinator** [comment]
This is fixed in 1.1.2 https://github.com/vanstinator/core-manager/releases/tag/1.1.2
